
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'airbnb'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'airbnb'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"] # asset 폴더 추가(이미지 등)
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

# dbt run 시작시, audit_log가 존재하는지 체크하고 생성
on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log (
      model_name STRING,
      run_timestamp TIMESTAMP
    )"


models:
  airbnb:
    +grants : 
      select: ["transform", "reporter"] # role에 대한 권한부여 가능. hook없이... 근데 이러면 yml에 권한이 노출되는 단점이 있음.
    +post-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)" # 모델이 빌드된 후, audit_log에 모델 이름과 빌드 시점 기록"
    # Config indicated by + and applies to all files under models/example/
    +materialized: view ## default가 view로 매터리얼라이제이션
    dim : 
      +materialized: table ## dim 하위 모델은 테이블로 매터리얼라이제이션
    src :
      +materialized: ephemeral ## src 하위 모델은 ephemeral로 매터리얼라이제이션

data_tests:
  +store_failures : true # 테스트 실패 시 실패한 레코드를 저장하는 설정. 실패한 레코드는 target/ 디렉토리에 저장됨. 이 설정을 통해 어떤 데이터가 테스트를 통과하지 못했는지 분석할 수 있음.
  +schema: _test_failures # 실패한 레코드를 저장할 스키마 이름. 기본값은 _dbt_test_failures. 이 설정을 통해 실패한 레코드를 별도의 스키마에 저장하여 관리할 수 있음.